services:
  alloy:
    image: grafana/alloy
    container_name: alloy
    hostname: "nl"
    restart: unless-stopped
    networks:
      - nl
    ports:
      - "12345:12345"
    volumes:
      - alloy_data:/var/lib/alloy/data
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - nl
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - nl
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)


volumes:
  alloy_data:

networks:
  nl:
    driver: bridge